### ISSUE TITLE
Old Combat Mechanics conflicts with bed wars plugin.

### ISSUE THREAD

**Issue by LeehamElectronics** [kernitus/BukkitOldCombatMechanics#396]
Information
Version of the Server: Paper (312) 1.15.2 
Version of OldCombatMechanics: 1.8.0 

* Server Log File: 
[15:23:58 ERROR]: Error occurred while enabling MBedwars v4.0.17.1 (Is it up to date?)
java.lang.NoClassDefFoundError: gvlfm78/plugin/OldCombatMechanics/module/ModuleFishingKnockback
        at de.marcely.bedwars.df.onEnable(OldCombatMechanics.java:20) ~[?:?]
        at de.marcely.bedwars.dd.b(LibraryManager.java:73) ~[?:?]
        at de.marcely.bedwars.dd.loadLibraries(LibraryManager.java:37) ~[?:?]
        at de.marcely.bedwars.MBedwars.onEnable(MBedwars.java:132) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-312]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.15.2.jar:git-Paper-312]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-312]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472) ~[patched_1.15.2.jar:git-Paper-312]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386) ~[patched_1.15.2.jar:git-Paper-312]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-312]        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-312]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:900) ~[patched_1.15.2.jar:git-Paper-312]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.ClassNotFoundException: gvlfm78.plugin.OldCombatMechanics.module.ModuleFishingKnockback
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_251]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.15.2.jar:git-Paper-312]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.15.2.jar:git-Paper-312]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
        ... 13 more

* OldCombatMechanics config file: The default config. I have also reset it and reloaded the plugin.

## Problem Description
When I have old combat mechanics enabled it prevents my bed wars plugin from loading. I am assuming it is because of the Old Combat Mechanics plugin becuase of the messages in the console. Any help would be really appreciated!
Thanks so much.

1. Install both old combat mechanics and Marcely's Bedwars (latest version)

**Comment by detobel36** [comment]
I think it is a bug of Marcely's Bedwars due to update of OldCombatMechanics...

**Comment by kernitus** [comment]
This is a problem with some strange way that Bedwars seems to do 'integration' with OCM. Please contact them directly as there is nothing we can do here.
