### ISSUE TITLE
Golden Apple NamespacedKey NoClassDefFoundError

### ISSUE THREAD

**Issue by samukatb** [kernitus/BukkitOldCombatMechanics#411]
[01:48:58 ERROR]: Could not pass event PlayerItemConsumeEvent to OldCombatMechanics v1.8.0
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [Spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [Spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
at net.minecraft.server.v1_10_R1.EntityLiving.v(EntityLiving.java:2255) [Spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
at net.minecraft.server.v1_10_R1.EntityPlayer.v(EntityPlayer.java:939) [Spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
at net.minecraft.server.v1_10_R1.EntityLiving.cz(EntityLiving.java:2174) [Spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
at net.minecraft.server.v1_10_R1.EntityLiving.m(EntityLiving.java:1745) [Spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
at net.minecraft.server.v1_10_R1.EntityHuman.m(EntityHuman.java:142) [Spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
at net.minecraft.server.v1_10_R1.EntityPlayer.k_(EntityPlayer.java:242) [Spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
at net.minecraft.server.v1_10_R1.PlayerConnection.E_(PlayerConnection.java:138) [Spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
at net.minecraft.server.v1_10_R1.NetworkManager.a(NetworkManager.java:233) [Spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
at net.minecraft.server.v1_10_R1.ServerConnection.c(ServerConnection.java:140) [Spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:827) [Spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [Spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [Spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [Spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/NamespacedKey
at kernitus.plugin.OldCombatMechanics.module.ModuleGoldenApple.onItemConsume(ModuleGoldenApple.java:166) ~[?:?]
at sun.reflect.GeneratedMethodAccessor716.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[Spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
... 17 more

**Comment by kernitus** [comment]
This seems to be an issue with 1.10 not having the NamespacedKey class. I thought we wrapped those calls to support both pre-1.13 and onwards...

**Comment by I-Al-Istannen** [comment]
> This seems to be an issue with 1.10 not having the NamespacedKey class. I thought we wrapped those calls to support both pre-1.13 and onwards...

Somebody added the advancement stuff, which uses them unguarded. The material itself is versioned.
