### ISSUE TITLE
NoSuchFieldError: AWKWARD

### ISSUE THREAD

**Issue by Alveral** [kernitus/BukkitOldCombatMechanics#477]
## Information

* Server Version: Spigot 1.9

* OldCombatMechanics version: 1.8.1

* Server Log File: 
[16:18:32 ERROR]: Error occurred while enabling OldCombatMechanics v1.8.1 (Is it up to date?)
java.lang.NoSuchFieldError: AWKWARD
        at kernitus.plugin.OldCombatMechanics.module.ModuleOldPotionEffects.<clinit>(ModuleOldPotionEffects.java:39) ~[?:?]
        at kernitus.plugin.OldCombatMechanics.OCMMain.registerModules(OCMMain.java:160) ~[?:?]
        at kernitus.plugin.OldCombatMechanics.OCMMain.onEnable(OCMMain.java:55) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[spigot.jar:git-Spigot-7d15d07-c194444]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-7d15d07-c194444]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-7d15d07-c194444]
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361) [spigot.jar:git-Spigot-7d15d07-c194444]
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:411) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:376) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:331) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:269) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:522) [spigot.jar:git-Spigot-7d15d07-c194444]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]

* OldCombatMechanics config file: Didn't change anything anywhere, I just wanted to use this plugin only and I havent been busy with plugins lately so I'm bit out of this stuff, just want to use 1.8 pvp in an 1.9 server.

Hope anyone can help me solving this, probably it's something stupid/easy, sorry for wasting your time haha

Luuk

**Comment by Giacomo213342** [comment]
Same thing for me, but I have 1.12.2

**Comment by kernitus** [comment]
I don't have this problem when running with those versions. Also, the AWKWARD potion definitely was in the API for those versions...
