### ISSUE TITLE
Spartan regen check noclassdeffounderror

### ISSUE THREAD

**Issue by XBlowmPow3r** [kernitus/BukkitOldCombatMechanics#487]
[00:24:02 ERROR]: Could not pass event EntityRegainHealthEvent to OldCombatMechanics v1.9.0
java.lang.NoClassDefFoundError: me/vagdedes/spartan/system/Enums$HackType
        at kernitus.plugin.OldCombatMechanics.module.ModulePlayerRegen.disableSpartanRegenCheck(ModulePlayerRegen.java:95) ~[?:?]
        at kernitus.plugin.OldCombatMechanics.module.ModulePlayerRegen.onRegen(ModulePlayerRegen.java:74) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor263.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-444]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-444]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-444]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-444]
        at net.minecraft.server.v1_16_R3.EntityLiving.heal(EntityLiving.java:1054) ~[patched_1.16.5.jar:git-Paper-444]
        at net.minecraft.server.v1_16_R3.FoodMetaData.a(FoodMetaData.java:72) ~[patched_1.16.5.jar:git-Paper-444]
        at net.minecraft.server.v1_16_R3.EntityHuman.tick(EntityHuman.java:164) ~[patched_1.16.5.jar:git-Paper-444]
        at net.minecraft.server.v1_16_R3.EntityPlayer.playerTick(EntityPlayer.java:514) ~[patched_1.16.5.jar:git-Paper-444]
        at net.minecraft.server.v1_16_R3.PlayerConnection.tick(PlayerConnection.java:176) ~[patched_1.16.5.jar:git-Paper-444]
        at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:390) ~[patched_1.16.5.jar:git-Paper-444]
        at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:145) ~[patched_1.16.5.jar:git-Paper-444]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1380) ~[patched_1.16.5.jar:git-Paper-444]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.5.jar:git-Paper-444]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1208) ~[patched_1.16.5.jar:git-Paper-444]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:996) ~[patched_1.16.5.jar:git-Paper-444]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.5.jar:git-Paper-444]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]

## Information

* Server Version: 

* OldCombatMechanics version: 

* Server Log File: 

* OldCombatMechanics config file: 

### To Reproduce
1.
2.
3.

**Comment by kernitus** [comment]
Do you have Spartan anticheat enabled?
