### ISSUE TITLE
console spam

### ISSUE THREAD

**Issue by D3OXY** [kernitus/BukkitOldCombatMechanics#508]
[12:08:49 ERROR]: Could not pass event EntityRegainHealthEvent to OldCombatMechanics v1.9.0
java.lang.NoClassDefFoundError: me/vagdedes/spartan/system/Enums$HackType
        at kernitus.plugin.OldCombatMechanics.module.ModulePlayerRegen.disableSpartanRegenCheck(ModulePlayerRegen.java:95) ~[?:?]
        at kernitus.plugin.OldCombatMechanics.module.ModulePlayerRegen.onRegen(ModulePlayerRegen.java:74) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor51.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-542]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-542]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-542]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-542]
        at net.minecraft.server.v1_16_R3.EntityLiving.heal(EntityLiving.java:1055) ~[patched_1.16.5.jar:git-Paper-542]
        at net.minecraft.server.v1_16_R3.EntityLiving.heal(EntityLiving.java:1044) ~[patched_1.16.5.jar:git-Paper-542]
        at net.minecraft.server.v1_16_R3.FoodMetaData.a(FoodMetaData.java:85) ~[patched_1.16.5.jar:git-Paper-542]
        at net.minecraft.server.v1_16_R3.EntityHuman.tick(EntityHuman.java:164) ~[patched_1.16.5.jar:git-Paper-542]
        at net.minecraft.server.v1_16_R3.EntityPlayer.playerTick(EntityPlayer.java:518) ~[patched_1.16.5.jar:git-Paper-542]
        at net.minecraft.server.v1_16_R3.PlayerConnection.tick(PlayerConnection.java:178) ~[patched_1.16.5.jar:git-Paper-542]
        at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:390) ~[patched_1.16.5.jar:git-Paper-542]
        at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:145) ~[patched_1.16.5.jar:git-Paper-542]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1389) ~[patched_1.16.5.jar:git-Paper-542]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:379) ~[patched_1.16.5.jar:git-Paper-542]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1216) ~[patched_1.16.5.jar:git-Paper-542]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1004) ~[patched_1.16.5.jar:git-Paper-542]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.5.jar:git-Paper-542]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by kernitus** [comment]
Do you use spartan anti-cheat by any chance?
