### ISSUE TITLE
Netherite tools not accounted for

### ISSUE THREAD

**Issue by Marcuri02** [kernitus/BukkitOldCombatMechanics#537]
## Information

* Server Version: 1.17

* OldCombatMechanics version: 1.10.0.BETA

* Server Log File: 

* OldCombatMechanics config file: 

### To Reproduce
Don't know

### Actual Behaviour

```
[22:30:49 ERROR]: Could not pass event OCMEntityDamageByEntityEvent to OldCombatMechanics v1.10.0BETA
java.lang.IllegalArgumentException: No enum constant kernitus.plugin.OldCombatMechanics.utilities.damage.ToolDamage.NETHERITE_SWORD
        at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
        at kernitus.plugin.OldCombatMechanics.utilities.damage.ToolDamage.valueOf(ToolDamage.java:8) ~[?:?]
        at kernitus.plugin.OldCombatMechanics.utilities.damage.ToolDamage.getDamage(ToolDamage.java:23) ~[?:?]
        at kernitus.plugin.OldCombatMechanics.utilities.damage.ToolDamage.getDamage(ToolDamage.java:27) ~[?:?]
        at kernitus.plugin.OldCombatMechanics.module.ModuleOldToolDamage.onEntityDamaged(ModuleOldToolDamage.java:50) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor56.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.jar:git-Purpur-1197]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.17.jar:git-Purpur-1197]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.jar:git-Purpur-1197]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.jar:git-Purpur-1197]
        at kernitus.plugin.OldCombatMechanics.utilities.damage.EntityDamageByEntityListener.onEntityDamage(EntityDamageByEntityListener.java:41) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor64.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.jar:git-Purpur-1197]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.17.jar:git-Purpur-1197]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.jar:git-Purpur-1197]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.jar:git-Purpur-1197]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:242) ~[patched_1.17.jar:git-Purpur-1197]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1097) ~[patched_1.17.jar:git-Purpur-1197]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:981) ~[patched_1.17.jar:git-Purpur-1197]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:936) ~[patched_1.17.jar:git-Purpur-1197]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1129) ~[patched_1.17.jar:git-Purpur-1197]
        at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2076) ~[?:?]
        at net.minecraft.world.entity.player.Player.damageEntity0(Player.java:1060) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1374) ~[?:?]
        at net.minecraft.world.entity.player.Player.hurt(Player.java:967) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1024) ~[?:?]
        at net.minecraft.world.entity.player.Player.attack(Player.java:1304) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2094) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$5.onAttack(ServerGamePacketListenerImpl.java:2547) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2472) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.jar:git-Purpur-1197]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[patched_1.17.jar:git-Purpur-1197]
        at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:193) ~[patched_1.17.jar:git-Purpur-1197]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[patched_1.17.jar:git-Purpur-1197]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[patched_1.17.jar:git-Purpur-1197]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1468) ~[patched_1.17.jar:git-Purpur-1197]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1261) ~[patched_1.17.jar:git-Purpur-1197]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.jar:git-Purpur-1197]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by kernitus** [comment]
Fixed with 12cb6c3
