### ISSUE TITLE
Error in console spam

### ISSUE THREAD

**Issue by sebastiaannnn** [kernitus/BukkitOldCombatMechanics#584]
Hey im having the following error on my minigames server:

```
14:47:26 ERROR]: Could not pass event PotionSplashEvent to OldCombatMechanics v1.10.0
java.lang.NullPointerException: Cannot invoke "kernitus.plugin.OldCombatMechanics.utilities.potions.PotionDurations.getSplash()" because the return value of "java.util.HashMap.get(Object)" is null
at kernitus.plugin.OldCombatMechanics.module.ModuleOldPotionEffects.getPotionDuration(ModuleOldPotionEffects.java:193) ~[?:?]
at kernitus.plugin.OldCombatMechanics.module.ModuleOldPotionEffects.onPotionSplash(ModuleOldPotionEffects.java:135) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor106.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-792]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-792]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-792]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-792]
at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPotionSplashEvent(CraftEventFactory.java:786) ~[patched_1.16.5.jar:git-Paper-792]
at net.minecraft.server.v1_16_R3.EntityPotion.a(EntityPotion.java:184) ~[patched_1.16.5.jar:git-Paper-792]
at net.minecraft.server.v1_16_R3.EntityPotion.a(EntityPotion.java:113) ~[patched_1.16.5.jar:git-Paper-792]
at net.minecraft.server.v1_16_R3.IProjectile.preOnHit(IProjectile.java:141) ~[patched_1.16.5.jar:git-Paper-792]
at net.minecraft.server.v1_16_R3.EntityProjectile.tick(EntityProjectile.java:70) ~[patched_1.16.5.jar:git-Paper-792]
at net.minecraft.server.v1_16_R3.WorldServer.entityJoinedWorld(WorldServer.java:960) ~[patched_1.16.5.jar:git-Paper-792]
at net.minecraft.server.v1_16_R3.World.a(World.java:955) ~[patched_1.16.5.jar:git-Paper-792]
at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:646) ~[patched_1.16.5.jar:git-Paper-792]
at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1495) ~[patched_1.16.5.jar:git-Paper-792]
at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-792]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1347) ~[patched_1.16.5.jar:git-Paper-792]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1135) ~[patched_1.16.5.jar:git-Paper-792]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-792]
at java.lang.Thread.run(Thread.java:831) [?:?]
[14:47:26 INFO]: [Default] NingaKiller90: i serrabder
```

I already tried disabling the potion option, but didn't work

**Comment by nivcoo** [comment]
Do you use the plugin in 1.18 ?
