### ISSUE TITLE
Cannot read field "inventoryContents" because "info" is null after /oldcombatmechanics test finishes

### ISSUE THREAD

**Issue by wattywatty14** [kernitus/BukkitOldCombatMechanics#648]
Server Version: Current: git-Purpur-1922 (MC: 1.19.3)

`[00:34:51] [Server thread/INFO]: wattywatty14 issued server command: /oldcombatmechanics test wattywatty14
[00:35:13] [Server thread/WARN]: [OldCombatMechanics] Task #956 for OldCombatMechanics v1.11.0 generated an exception
java.lang.NullPointerException: Cannot read field "inventoryContents" because "info" is null
	at kernitus.plugin.OldCombatMechanics.tester.InGameTester.afterAll(InGameTester.java:164) ~[OldCombatMechanics.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.3.jar:git-Purpur-1922]
	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.3.jar:git-Purpur-1922]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1500) ~[purpur-1.19.3.jar:git-Purpur-1922]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:488) ~[purpur-1.19.3.jar:git-Purpur-1922]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.3.jar:git-Purpur-1922]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.3.jar:git-Purpur-1922]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1922]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by rayzr522** [comment]
please try out [the latest development build](https://ci.rayzr.dev/job/OldCombatMechanics/) and let us know if this has solved your issue. thanks :3

**Comment by wattywatty14** [comment]
So - /ocm test doesn't exist anymore apparently. When I type /ocm I get the following error. 

`[05:17:34] [Server thread/INFO]: wattywatty14 issued server command: /ocm test
[05:17:39] [Server thread/INFO]: wattywatty14 issued server command: /ocm test
[05:17:40] [Server thread/INFO]: wattywatty14 issued server command: /ocm test wa
[05:18:13] [Server thread/INFO]: wattywatty14 issued server command: /ocm test wattywatty14
[05:18:15] [Server thread/INFO]: wattywatty14 issued server command: /ocm test
[05:18:17] [Server thread/INFO]: wattywatty14 issued server command: /ocm help
[05:18:17] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ocm' in plugin OldCombatMechanics v2.0.0BETA
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:926) ~[purpur-1.19.3.jar:git-Purpur-1922]
	at org.bukkit.craftbukkit.v1_19_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[purpur-1.19.3.jar:git-Purpur-1922]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[purpur-1.19.3.jar:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:324) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:308) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2379) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$21(ServerGamePacketListenerImpl.java:2339) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.3.jar:git-Purpur-1922]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.3.jar:git-Purpur-1922]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.19.3.jar:git-Purpur-1922]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.3.jar:git-Purpur-1922]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.3.jar:git-Purpur-1922]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1316) ~[purpur-1.19.3.jar:git-Purpur-1922]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[purpur-1.19.3.jar:git-Purpur-1922]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1922]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: No enum constant kernitus.plugin.OldCombatMechanics.commands.OCMCommandHandler.Subcommand.help
	at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
	at kernitus.plugin.OldCombatMechanics.commands.OCMCommandHandler$Subcommand.valueOf(OCMCommandHandler.java:34) ~[OldCombatMechanics (1).jar:?]
	at kernitus.plugin.OldCombatMechanics.commands.OCMCommandHandler.onCommand(OCMCommandHandler.java:133) ~[OldCombatMechanics (1).jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	... 23 more
`

**Comment by kernitus** [comment]
I have no idea why you are trying to run `/ocm test`, that is only for internal testing purposes. It was made to work with Spigot version 1.19.2 and nothing else.
