### ISSUE TITLE
BSON serialisation error

### ISSUE THREAD

**Issue by LeCraft2Ouf** [kernitus/BukkitOldCombatMechanics#727]
## Information
* Server Version: 1.18.2

* OldCombatMechanics version: v2.0.2-beta

* Server Log File: 
<details><summary>Server Log</summary>
  
``` [22:57:58] [Server thread/INFO]: [OldCombatMechanics] Enabling OldCombatMechanics v2.0.2-beta
[22:57:59] [Server thread/ERROR]: Error occurred while enabling OldCombatMechanics v2.0.2-beta (Is it up to date?)
org.bson.BsonSerializationException: While decoding a BSON document 4 bytes were required, but only 0 remain
	at org.bson.io.ByteBufferBsonInput.ensureAvailable(ByteBufferBsonInput.java:208) ~[OldCombatMechanics.jar:?]
	at org.bson.io.ByteBufferBsonInput.readInt32(ByteBufferBsonInput.java:104) ~[OldCombatMechanics.jar:?]
	at org.bson.BsonBinaryReader.readSize(BsonBinaryReader.java:380) ~[OldCombatMechanics.jar:?]
	at org.bson.BsonBinaryReader.doReadStartDocument(BsonBinaryReader.java:274) ~[OldCombatMechanics.jar:?]
	at org.bson.AbstractBsonReader.readStartDocument(AbstractBsonReader.java:450) ~[OldCombatMechanics.jar:?]
	at org.bson.codecs.DocumentCodec.decode(DocumentCodec.java:173) ~[OldCombatMechanics.jar:?]
	at kernitus.plugin.OldCombatMechanics.utilities.storage.PlayerStorage.loadData(PlayerStorage.java:69) ~[OldCombatMechanics.jar:?]
	at kernitus.plugin.OldCombatMechanics.utilities.storage.PlayerStorage.initialise(PlayerStorage.java:58) ~[OldCombatMechanics.jar:?]
	at kernitus.plugin.OldCombatMechanics.OCMMain.onEnable(OCMMain.java:65) ~[OldCombatMechanics.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[paper-1.18.2.jar:git-Paper-"f22f4dd"]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.18.2.jar:git-Paper-"f22f4dd"]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:665) ~[paper-1.18.2.jar:git-Paper-"f22f4dd"]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:432) ~[paper-1.18.2.jar:git-Paper-"f22f4dd"]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-"f22f4dd"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164) ~[paper-1.18.2.jar:git-Paper-"f22f4dd"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-"f22f4dd"]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
[22:57:59] [Server thread/INFO]: [OldCombatMechanics] Disabling OldCombatMechanics v2.0.2-beta
[22:57:59] [Server thread/ERROR]: Error occurred while disabling OldCombatMechanics v2.0.2-beta (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "java.util.Map.containsKey(Object)" because "document" is null
	at org.bson.codecs.DocumentCodec.beforeFields(DocumentCodec.java:190) ~[OldCombatMechanics.jar:?]
	at org.bson.codecs.DocumentCodec.encode(DocumentCodec.java:157) ~[OldCombatMechanics.jar:?]
	at kernitus.plugin.OldCombatMechanics.utilities.storage.PlayerStorage.instantSave(PlayerStorage.java:89) ~[OldCombatMechanics.jar:?]
	at kernitus.plugin.OldCombatMechanics.OCMMain.onDisable(OCMMain.java:179) ~[OldCombatMechanics.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:578) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[paper-1.18.2.jar:git-Paper-"f22f4dd"]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.18.2.jar:git-Paper-"f22f4dd"]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:665) ~[paper-1.18.2.jar:git-Paper-"f22f4dd"]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:432) ~[paper-1.18.2.jar:git-Paper-"f22f4dd"]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-"f22f4dd"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164) ~[paper-1.18.2.jar:git-Paper-"f22f4dd"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-"f22f4dd"]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]```
</details>

**Comment by kernitus** [comment]
Is your `plugins/OldCombatMechanics/players.bson` file present?
