### ISSUE TITLE
ignore and/or dlete post as it was my fault

### ISSUE THREAD

**Issue by DeathRyder35** [kernitus/BukkitOldCombatMechanics#733]
[21:02:13] [Netty Epoll Server IO #3/WARN]: [OldCombatMechanics] Error in a packet listener (send).
java.lang.NullPointerException: Cannot invoke "java.util.Optional.isPresent()" because "structOptional" is null
	at kernitus.plugin.OldCombatMechanics.utilities.packet.team.V17TeamPacket$PacketAccess.lambda$setCollisionRule$4(V17TeamPacket.java:121) ~[OldCombatMechanics.jar:?]
	at kernitus.plugin.OldCombatMechanics.utilities.reflection.Reflector.getUnchecked(Reflector.java:294) ~[OldCombatMechanics.jar:?]
	at kernitus.plugin.OldCombatMechanics.utilities.packet.team.V17TeamPacket$PacketAccess.setCollisionRule(V17TeamPacket.java:117) ~[OldCombatMechanics.jar:?]
	at kernitus.plugin.OldCombatMechanics.utilities.packet.team.V17TeamPacket.withCollisionRule(V17TeamPacket.java:32) ~[OldCombatMechanics.jar:?]
	at kernitus.plugin.OldCombatMechanics.module.ModulePlayerCollisions$CollisionPacketListener.handlePacket(ModulePlayerCollisions.java:172) ~[OldCombatMechanics.jar:?]
	at kernitus.plugin.OldCombatMechanics.module.ModulePlayerCollisions$CollisionPacketListener.onPacketSend(ModulePlayerCollisions.java:141) ~[OldCombatMechanics.jar:?]
	at kernitus.plugin.OldCombatMechanics.utilities.packet.mitm.PacketInjector.write(PacketInjector.java:187) ~[OldCombatMechanics.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1015) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:301) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:210) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:199) ~[ProtocolLib.jar:?]
	at net.minecraft.network.Connection.doSendPacket(Connection.java:449) ~[?:?]
	at net.minecraft.network.Connection.lambda$sendPacket$10(Connection.java:434) ~[?:?]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48) ~[ProtocolLib.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]

paper 1.20.4
latest plugin
just fight a player and it fills console

**Comment by DeathRyder35** [comment]
ffs you know what exactly latest is XD OldCombatMechanics - Disable 1.9 hit cooldown 2.0.1 better?

**Comment by kernitus** [comment]
Well no, I don't know what "latest" means, as this changes quite frequently and there are multiple places where you might've gotten the plugin. In fact, the version you're using is _not_ the latest, because this issue was already fixed in the newer versions you can find on [Jenkins](https://ci.rayzr.dev/job/OldCombatMechanics/).

**Comment by DeathRyder35** [comment]
Yea I just saw that last nite, as I didn't put it in the server, meant to
apologize for bein a dick, I'm sorry for bein a dick, just got alot of
things to do XD
