### ISSUE TITLE
Empty string is not working

### ISSUE THREAD

**Issue by ga6rielsilva** [kernitus/BukkitOldCombatMechanics#750]
## Information

* Server Version: 1.21

* OldCombatMechanics version: 2.0.2

* A blank message is sent in chat when someone change modeset/join the server.
![image](https://github.com/user-attachments/assets/28e258aa-64dc-4916-9c86-f5d453d455b2)
![image](https://github.com/user-attachments/assets/bfaa4d68-c5d6-4ec7-b7fe-defa901bec68)
![image](https://github.com/user-attachments/assets/04a028ed-60e8-4a7a-9b1c-e076a57cad8f)

* I'm also getting this error in server startup
<details>
``` console
[02:39:19 INFO]: [OldCombatMechanics] Enabling OldCombatMechanics v2.0.2
[02:39:19 ERROR]: [OldCombatMechanics] [STDERR] Failed to load Reflector
[02:39:19 WARN]: Nag author(s): '[kernitus, Rayzr522]' of 'OldCombatMechanics v2.0.2' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).
[02:39:19 WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
[02:39:19 WARN]:        at OldCombatMechanics.jar//kernitus.plugin.OldCombatMechanics.utilities.reflection.Reflector.<clinit>(Reflector.java:32)
[02:39:19 WARN]:        at OldCombatMechanics.jar//kernitus.plugin.OldCombatMechanics.OCMMain.registerModules(OCMMain.java:196)
[02:39:19 WARN]:        at OldCombatMechanics.jar//kernitus.plugin.OldCombatMechanics.OCMMain.onEnable(OCMMain.java:85)
[02:39:19 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[02:39:19 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[02:39:19 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[02:39:19 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[02:39:19 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:644)
[02:39:19 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:593)
[02:39:19 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:752)
[02:39:19 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:511)
[02:39:19 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:333)
[02:39:19 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214)
[02:39:19 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325)
[02:39:19 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[02:39:19 INFO]: [PlaceholderAPI] Successfully registered internal expansion: ocm [2.0.2]
[02:39:19 INFO]: [OldCombatMechanics] OldCombatMechanics v2.0.2 has been enabled
```
</details>

**Comment by kernitus** [comment]
These issues were fixed months ago in the test versions. I will release a new official version to make it clearer.
